### ISSUE TITLE
这个reply 什么意思?

### ISSUE THREAD

**Issue by ydf** [felix021/ssocks5#1]
```
            reply += socket.inet_aton('0.0.0.0') + struct.pack(">H", 2222)
```

**Comment by felix021** [comment]
推荐学习Socks5协议原文 http://www.openssh.com/txt/rfc1928.txt

**Comment by ydf** [comment]
不是很理解 为什么返回这个ip (有点理解)和 2222的(搞不明白),能不能帮我解释下  谢谢

**Comment by ydf** [comment]
英文 读的不是很好

**Comment by felix021** [comment]
一般用不到，所以估计shadowsocks只是随便填了一个上去。

   In the reply to a CONNECT, BND.PORT contains the port number that the
   server assigned to connect to the target host, while BND.ADDR
   contains the associated IP address.  The supplied BND.ADDR is often
   different from the IP address that the client uses to reach the SOCKS
   server, since such servers are often multi-homed.  It is expected
   that the SOCKS server will use DST.ADDR and DST.PORT, and the
   client-side source address and port in evaluating the CONNECT
   request.

**Comment by ydf** [comment]
可以这样理解吗? 返回代理服务器连接目标服务器  所 使用的ip和port.

**Comment by felix021** [comment]
嗯 就是这个意思。
